#!/usr/bin/env ruby

require 'kris'

if ENV['KRIS_ENV'] == 'production'
  config = {
    server:   ENV['IRC_SERVER'],
    port:     ENV['IRC_PORT'],
    channel:  ENV['IRC_CHANNEL'],
    channels: ENV['IRC_CHANNELS'].split(','),
    username: ENV['IRC_NICK'],
    nickname: ENV['IRC_NICK'],
    realname: ENV['IRC_NICK']
  }
else
  config = {
    server:   'chat.freenode.net',
    port:     6667,
    channel:  '#rig',
    username: 'TomochanTest'
  }
end

Kris::Session.new(config).start
