#!/usr/bin/env ruby

require 'kris'

if ENV['KRIS_ENV'] == 'production'
  config = {
    server:   ENV['IRC_SERVER'],
    port:     ENV['IRC_PORT'],
    channel:  ENV['IRC_CHANNEL'],
    channels: ENV['IRC_CHANNELS'].split(','),
    nickname: ENV['IRC_NICK'],
    username: ENV['IRC_USER'],
    passowrd: ENV['IRC_PASS'],
    realname: ENV['IRC_USER'],
    use_ssl:  true
  }
else
  config = {
    server:   'chat.freenode.net',
    port:     6667,
    channel:  '#Tomohiro',
    username: 'Tomochan'
  }
end

Kris::Session.new(config).start
