#!/usr/bin/env ruby

require 'kris'

Kris::Session.new(
  :server   => ENV['IRC_SERVER'],
  :port     => ENV['IRC_PORT'],
  :channel  => ENV['IRC_CHANNEL'],
  :username => ENV['IRC_NICK'],
  :nickname => ENV['IRC_NICK'],
  :realname => ENV['IRC_NICK']
).start
